[package]
name = "pdblister"
version = "0.1.0"
authors = ["Gogs <gogs@fake.local>"]
edition = "2018"

[dependencies]
rand = "0.3"
futures = "0.3.5"
reqwest = "0.10.8"

[dependencies.tokio]
version = "0.2.22"
features = ["fs", "rt-threaded"]
